# Generated by Django 5.1.3 on 2024-12-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0012_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyć modele Osoba innych właścicieli')]},
        ),
    ]
